#http://localhost:8090/genogram/fanMenu/getMenuBySiteId?siteId=1
fan_api_web_service:
  ip: http://192.168.2.179:8090
  fastDfs_ip: http://192.168.2.132:8090
fan_api_admin_service:
  api_ip: http://192.168.2.179:8090
  fastDfs_ip: http://192.168.2.132:8090
pro_api_web_service:
  ip: http://192.168.2.179:8090
  fastDfs_ip: http://192.168.2.132:8090
server:
  port: 8070
spring:
  profiles:
    active: dev

