#http://localhost:8050/test/test1?username=ss&pwd=1
fan_api_admin_service:
  api_ip: http://192.168.2.179:8050
  fastDfs_ip: http://192.168.2.132:8090
server:
  port: 8050
spring:
  profiles:
    active: dev

