#http://localhost:8090/test/test1?username=ss&pwd=1
spring:
  profiles: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/genealogy?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 875Yhtpw758@
mybatis-plus:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 0
  mapper-locations: classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: com.genogram.entity
