#http://localhost:8090/genogram/fanMenu/getMenuBySiteId?siteId=1
fastDfs_ip: http://192.168.2.132:8090/
fan_api_web_service:
  pay_notify_url: http://192.168.2.179:8090/genogram/pay/notify_url
  pay_return_url: http://192.168.2.179:8090/genogram/pay/return_url
  fastDfs_ip: http://192.168.2.132:8090/

server:
  port: 8090
spring:
  profiles:
    active: dev